name: manhunt
version: 1.1
author: Lainad27
main: me.lainad27.manhunt.Main
api-version: 1.16

commands:
  hunter:
    description: make someone a hunter
  speeder:
    description: make someone a speedrunner
  start:
    description: start the game, argument is seconds. for example /start 30 will start with cooldown of 30 seconds
  togglesound:
    description: toggle hunter - speedrunner close range sound